### PR TITLE
Sv se

### PR DESCRIPTION
**Pull request by KallistiMan**

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks for this. Can you tell me what the file "termer.txt" is for. I don't think it's needed is it? If not, can you delete it please?

**Comment by KallistiMan** [comment]
That file is for terms (termer), to be consistent when translating. It's like a style guide for translating to Swedish, especially since terms like item, thing, device are very close. But I can delete it if you want.

**Comment by cdjackson** [comment]
Ok, understood…

The issue is that I will import these strings into a database that can be edited easily, and then I export the database directly into the HABmin compilation environment. This makes it easier to manage all the translation strings when something is updated in one of the base English files. Once this is done, this file will be lost so it’s probably better to remove if you don’t mind.

I do however see your point, and it might be a good idea to try and formalise what you’re trying to achieve here - maybe I can find a grunt task to swap these words to ensure consistency… This is something to look at a bit later though :)

**Comment by KallistiMan** [comment]
Don't think it's going to work grammatically to swap words unfortunately. I'll keep the file for myself for future reference and if someone else pitches in I guess they'll understand the gist of it by looking through the other files.

**Comment by cdjackson** [comment]
Ok - that’s fine…

By ‘swap words’ - I mean to provide a table like you have with your ‘terms’ and then instead of using the word ‘thing’, instead use something like {{{thing}}} and we then replace the {{{thing}}} with the definition in the ‘terms’ file…  I assume this is effectively what you are doing manually now?  Anyway, it was just a thought for the future...

**Comment by KallistiMan** [comment]
Hi again, 
That's what I thought you meant by swapping - unfortunately that's not going to work and it's not what I'm doing manually. When translating I have to grammatically conjugate the words, change word orders, understand what the string is intended to convey in it's context, not just it's literal meaning. Word replacing would not work for Swedish nor really, I would believe, any other language. 

On another note, I registered for a translation account on your site before I realised it was probably easier to just do the strings in a PR as it was for a new language. But could I suggest you look at transifex or some other service? Translations can really benefit from a larger community within a language, to keep Translations consistent and make it less confusing for users. Just a thought.

**Comment by cdjackson** [comment]
Hi,
I did look around at existing services before I wrote the one on my site but couldn’t find a good one that was free. transifex that you suggest is just way to expensive for me - I get no income from this, so paying $79 per month for this is out of the question I’m afraid.

I think the one of my site is ok - for some it might be easier to edit the json files, but for many it’s easier to use the web interface, and the feedback I’ve had has been very positive.

Chris

**Comment by KallistiMan** [comment]
I thought the transifex one was free for open source project, haven't researched it very much myself. Yours is perfectly fine, it seems to be very good. I just felt for me it would be easier to fork and go through all the files myself, as I couldn't see a way to create a new language on the site.

**Comment by cdjackson** [comment]
I didn’t see anything about OS projects being free, but maybe I missed it.

You are right - at the moment I need to create the language in the database to get started - I probably should add that to make things easier for users :)

**Pull request merged**
