### PR TITLE
feat(UI) Added French language

### PR DESCRIPTION
**Pull request by pierok13**
Add the french translation. Did not know if it's the right place to pull the request.

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks for this translation :)

**Comment by cdjackson** [comment]
Thanks :) I just did a quick test and it looks good. The only problem I see is the 'c' in Francais in the selection box is not showing correctly - everything else looks correct.  I'll have a look to see if I can fix this - this is defined in the code rather than the localisation files, so I might need to handle this differently.

**Comment by pierok13** [comment]
Great. For the time you still can let the c instead of the cedilla. 
As I see the translations were not taken in account in the zwave binding management ? Is this normal or did I miss something ?

**Comment by cdjackson** [comment]
The cedilla is fixed - for now at least. I’ve added a translation function to sort this out.

There’s an error in the zwave translation file - one of the strings is broken across a line. I’ve just pushed a fix for this and also the cedilla.  This also tested the translation fallback :)

Merci.

Chris

**Pull request merged**
